/**
 * @file ErrorCodes.h
 * @author Pablo Narvaja
 * @brief Here are all the error codes with its description.
 **/
#pragma once

#define GET_ERROR_MSG(code)                                              \
  std::string("\nerror_msg: ") + #code + std::string("\nerror_code: ") + \
      std::to_string(code)

#define ERROR_INSTANCE_ALREADY_RUNNING 1
#define ERROR_INDEX_OUT_OF_BOUNDS 2
#define ERROR_NULL_ARG 3

#define ERROR_GAME 10
#define ERROR_GAME_LIB_NOT_FOUND 11
#define ERROR_GAME_LIB_INVALID 12
#define ERROR_GAME_MAIN_NOT_FOUND 13

#define ERROR_INPUT 20
#define ERROR_INPUT_KEY_INVALID_VALUE 21

#define ERROR_GRAPHICS_API 30
#define ERROR_GRAPHICS_API_INITIALIZATION 31
#define ERROR_GRAPHICS_API_NOT_IMPLEMENTED 32

#define ERROR_THREADING 40
#define ERROR_THREADING_NO_LOCK 41

#define ERROR_PLATFORM 400
#define ERROR_PLATFORM_WINDOW_CREATION 401
#define ERROR_PLATFORM_WINDOWS_REGISTERCLASS 402
#define ERROR_PLATFORM_THREAD_CREATE 410

#define ERROR_PLATFORM_OPENGL_CONTEXT_INDIRECT 420
#define ERROR_PLATFORM_OPENGL_PIXELFORMAT 421
#define ERROR_PLATFORM_OPENGL_CREATE_FAILED 422
#define ERROR_PLATFORM_OPENGL_CREATE_MODERN_FAILED 423
#define ERROR_PLATFORM_OPENGL_PROC_NOT_FOUND 424
#define ERROR_PLATFORM_OPENGL_LIB_NOT_FOUND 425
#define ERROR_PLATFORM_OPENGL_GLX_VERSION 426
